version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
      - mvn sonar:sonar -Dsonar.projectKey=proyect00  -Dsonar.host.url=http://54.90.207.91  -Dsonar.login=d0bb7f2f65440f98153b22196f76c87f0911409a
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/messageUtil-1.0.jar